### ISSUE TITLE
Editor shows property type instead of name in "Try this operation"

### ISSUE THREAD

**Issue by bbbush** [swagger-api/swagger-editor#1039]
**Swagger File**

https://gist.githubusercontent.com/bbbush/342a65730a84eee7e0e80678aa67a62d/raw

**Issue**

I don't know if this is really an issue? It feels inconvenient if property type is displayed instead of property name.

**Comment by webron** [comment]
You mean it shows the reference name instead of the property name?

**Comment by bbbush** [comment]
Yes. Suppose this definition were referenced multiple times, it would be too hard to tell which property it is.
![swagger-editor-shows-property-type](https://cloud.githubusercontent.com/assets/45521/17534222/c6f5a5a0-5e4d-11e6-8b76-22a9774156c1.PNG)

**Comment by webron** [comment]
Yup, just making sure I understood correctly. It's indeed a bug.

**Comment by bbbush** [comment]
the try-operation code seems to prefer "title" attribute to the actual property name, and a reference happened to have a "title"? A workaround is to always use "allOf" and set a "title" (and description) in the last item, which would override any "title" in preceding siblings

**Comment by saharj** [comment]
I looked into it and here is what's happening:

Swagger Editor uses the key in `definitions` object for JSON Schemas with no title. If you provide a title for your JSON Schema that title will be used. 

* Definition `A` refers to a definition that has no title so the key in the definitions object (`"string-ref"`) is used
* Definition `B ` is result of merger of two JSON Schemas. One the referred one and the other one has the title `B`. When we merge `allOf`, the later wins so `"B"` becomes the title
* Definitions `C` is not having a title property so we're using the key in definitions 

All of this is expected behavior and I don't think it's a bug.

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
