### ISSUE TITLE
style.css is 22.5 MB?

### ISSUE THREAD

**Issue by brylie** [swagger-api/swagger-editor#1063]
* Version: 2.10.3
* Browser/OS: Chromium / Ubuntu

When rendering the Swagger Editor, we were noticing >~10 second page load times. The browser console shows that **style.css** blocks the page load for about 8 seconds, and costs 22MB in network transfer:

![screenshot from 2016-09-13 14-42-00](https://cloud.githubusercontent.com/assets/17307/18472538/bf5ecefa-79c0-11e6-8281-3d4ba5e82940.png)

Please consider optimizing/minifying the **style.css** rules, so they load faster.

**Comment by brylie** [comment]
Note, when inspecting the **style.css** I notice several base64 blobs. It might be that our server was compromised. What is the usual size of *style.css**?

**Comment by saharj** [comment]
We discussed this in https://github.com/swagger-api/swagger-editor/issues/991

It's not an easy fix because we want Swagger Editor work from any path in a server so all of it's resources should have relative paths. Configuring webpack to do that is something I wasn't able to do because of this bug: https://github.com/webpack/file-loader/issues/62
