### ISSUE TITLE
Comments in YAML are missing with the new version Swagger Editor

### ISSUE THREAD

**Issue by jenniferwang2000** [swagger-api/swagger-editor#1292]
If you open a YAML file with comments in the new version of Swagger Editor after you click Download YAML from the File menu. The comments in the downloaded YAML file are missing.

**Comment by shockey** [comment]
@webron, in order to support this, we'll have to change our "Download YAML" functionality to effectively be "Download editor content as YAML". 

Shouldn't hurt anything - just wanted you to know what'll be going on behind the scenes.

**Comment by jamesdaily** [comment]
I do think this should be fixed since comments are part of OpenAPI.

But in the meantime, to anyone else facing this (as I am), consider: Why do I need this comment in my spec? Isn't the spec descriptive enough by itself? Can I improve my descriptions, summaries, etc. so that this comment isn't needed? Is the need for a comment just a symptom of some flaw in my service definition, such as it's too large or confusing on its own?

There will sometimes be good reasons for comments, but maybe you can get by with fewer of them (and thus fewer workarounds needed while waiting for this bug to be fixed).
