### ISSUE TITLE
Nothing happens when I try to generate code for c# from the editor.

### ISSUE THREAD

**Issue by Joebeazelman** [swagger-api/swagger-editor#1577]
Nothing happens when I try to generate code for c#

**Comment by webron** [comment]
The issue template is there to help us help you. If you take the time to fill it, we'll be happy to take the time and help you out.

**Comment by Joebeazelman** [comment]
Well if you made it clear where it was, then it would be even more
helpful!  You want your users to do free beta testing and then cop an
attitude?

**Comment by webron** [comment]
The template is there when you file a new issue. You literally had to select it all and delete it in order to file the issue.

And no, I don't want 'my users' to do 'free beta testing'. This is a free product and an open source one. Use it at will. If you want our help, we'll do our best to offer it, but the least you can do is follow our structure.

**Comment by Joebeazelman** [comment]
Wow!  Service with a smirk.

Well I won't waste anymore of my time on a vapid product.  If it has any
swagger, it sure is a limp one.
