### ISSUE TITLE
Method to check if edited spec is valid

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [swagger-api/swagger-editor#1590]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Feature
| Which Swagger/OpenAPI version?      | 3.x
| Which Swagger-Editor version?       |3.x
| How did you install Swagger-Editor? | NPM
| Which broswer & version?            | Chrome
| Which operating system?             | Windows 10

Hello.

My company is developing portal and I'm integrating Swagger Editor there.

I was able to place Swagger Editor in my Servier Side Rendered webpage and loaded it with this code:

        window.onload = function () {

            // We load JSON spec from django
            var spec = {{ swagger|safe }};
            var yml = jsyaml.dump(spec);

            // Build a system
            const editor = SwaggerEditorBundle({
                dom_id: '#swagger-editor',
                layout: 'EditorLayout',
                disableFileMenu: true,
                presets: [
                    SwaggerEditorStandalonePreset
                ]
            });
            editor.specActions.updateSpec(yml);
            window.editor = editor;

            $("#swagger-save").click(function () {
                // WHAT TO DO HERE?
            });
        }

I have placed my button, that should send newly edited JSON spec to backend and now there is a problem. 

Before sending I need to check if editor has valid spec, how can I check it? Is there some kind of method in editor?

How it is possible to exctract newly edited spec's JSON?

**Comment by shockey** [comment]
Hi @SuperMasterBlasterLaser!

Try this on for size:

```js
const isValid = !(editor.errSelectors.allErrors().size)
```

This will be `true` if there are no errors stored in the Editor's state (i.e., the current content is valid) and `false` otherwise.

Word of caution: this API is pretty stable, however, changes to it are not considered breaking changes. This means that it may change in minor version updates, so plan your versioning accordingly.

Also, on an unrelated note, if you're using Swagger-Editor in a React application, it would be better to use the `swagger-editor` module than `swagger-editor-dist`. Module bundlers are able to make your bundle smaller that way :smile: 

Let me know if this helps!

**Comment by SuperMasterBlasterLaser** [comment]
@shockey 

Helllo. We have found the way to get edited spec.

    var yaml = localStorage.getItem('swagger-editor-content');

This lib uses LocalStorage in order to keep editing spec.

If you say that method to check if it is valid may change in future, we will just use YAML validation lib for now.

I think in future version's there should be methods that returns spec as YAML or JSON and returns validation results, because some developers will be trying to integrate Swagger Editor in their own Web applications, which could be based on other technologies, not only React.
