### ISSUE TITLE
Empty security field breaks the Swagger Editor

### ISSUE THREAD

**Issue by tnjohansson** [swagger-api/swagger-editor#1612]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       | Latest online editor
| How did you install Swagger-Editor? | Online
| Which broswer & version?            | Chrome Version 63.0.3239.108
| Which operating system?             | Windows 10

### Current Behavior

The following spec renders OK in the [online editor](https://editor.swagger.io/) 

``` json
openapi: 3.0.0
info:
  title: Test
  version: v0
security:
  - BasicAuth: []
paths:
  /ping:
    get:
      operationId: ping1
      description: Test
      responses:
        '200':
          description: OK
  /ping2:
    get:
      operationId: ping2
      description: Test
      responses:
        '200':
          description: OK          
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
```

But if add an empty **security** field to one of the endpoints it breaks the editor. Update the spec with the following 

``` json 
openapi: 3.0.0
info:
  title: Test
  version: v0
security:
  - BasicAuth: []
paths:
  /ping:
    get:
      operationId: ping1
      description: Test
      responses:
        '200':
          description: OK
  /ping2:
    get:
      operationId: ping2
      description: Test
      security: 
        - 
      responses:
        '200':
          description: OK          
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
```

At this point, the editor is not showing any issues but I cannot expand the `/ping2` endpoint. Removing the empty `security` field does not fix the issue. If I then **reload the browser** the spec fails to render and I see the following.  

![image](https://user-images.githubusercontent.com/10422956/34480529-de02eff2-efa4-11e7-9369-0d6914296cd6.png)

The editor seems to be in an error state which it cannot recover from. Even if I past the PetStore spec into the editor it fails to generate the spec. 

![image](https://user-images.githubusercontent.com/10422956/34480577-1f6fc0f0-efa5-11e7-96f3-a0ec64c0aab0.png)

The only way to get out of this is to; 
- **Clear the editor** (File/Clear Editor)
- **Refresh the browser**

**Comment by shockey** [comment]
This is being caused by a TypeError in the `isAuthorized` auth selector, which expects `securities.toJS()` to yield an array:

https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/auth/selectors.js#L82

We could fix this by doing more type-checking or providing fallback values in that selector, or even avoiding converting from the Immutable data structure in the first place... but what we really need to do is try/catch the Redux code, so that any error within the Redux bits doesn't bring down the entire application (see https://github.com/swagger-api/swagger-ui/issues/3362). This generalized solution is good because a large amount of the application runs on arbitrary user inputs, so we can't realistically hope to cover every possible case.

**Comment by shockey** [comment]
Oh, also, I _did_ fix this specific case in a Swagger-UI PR that's still unmerged: https://github.com/swagger-api/swagger-ui/issues/4054.... but the general solution still needs to happen :smile: 

Thanks for filing this, @tnjohansson!

**Comment by shockey** [comment]
Fixed! This will be live on Friday evening.

Thanks for the report, @tnjohansson!
