### ISSUE TITLE
Cache Example Value error

### ISSUE THREAD

**Issue by Steve-hyas** [swagger-api/swagger-editor#1748]
I was trying to modify the "Example Value" section and found it was never changing, regardless of how stripped down the config file was

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      |  2.0
| Which Swagger-Editor version?       | Online
| How did you install Swagger-Editor? | Online
| Which browser & version?            | Chrome / Firefox
| Which operating system?             | Ubuntu

### Demonstration API definition
```yaml
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          type: string
      responses:
        405:
          description: "Invalid input"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
```

Screenshot of two browsers, showing the same code above

![image](https://user-images.githubusercontent.com/22966511/39444198-cbb42e00-4c6b-11e8-8c90-8ba621d946f9.png)

Code is the sample petstore, I changed the `schema` to a string rather then the object. The one I modified (on left) never updates the example value, Even if I cut away all the code and paste it back in again. The one I opened in a different browser shows the correct value.

**Comment by shockey** [comment]
Diagnosis!

Parameter values are stored in Redux state, which causes the following to happen when replacing `$ref: "#/definitions/Pet"` with `type: string`:
- Before the change happens, the object example value has been stored in application state as the current value for the parameter (so it could be used, for example, if the user clicked Execute instead of changing the definition data)
- When the change happens, the resolved subtrees are flushed from the application state, which causes the ModelExample component (along with everything else in the operation) to unmount.
- Once the new data has been resolved, the ModelExample component and body form mount again. Since the parameter already has a value stored (the old example), ModelExample uses that value instead of generating a fresh example.

The crux of the issue is that ModelExample has no way to know whether it's mounting for the first time/in response to a schema change (which would call for a fresh example value), or mounting because an operation was collapsed and expanded again (which would call for retaining the previous value, optimally).

Possible solutions:
- Always reset the form to the example value when mounting the component. This solves the issue, but would also cause the body value to be wiped when collapsing an operation, which is a slightly degraded UX.
- Batch the flushing and updating of the resolved subtree values, so that the operation components don't unmount. This is the most correct way to do this, but could introduce some unrelated bugs, so it will need manual testing.
- Index stored parameter values by a key that would change if the parameter's schema changed, so that these collisions don't happen. Effective and narrow solution, but makes the way we store parameters less intuitive.

---

I'm going to kick this to next week - @webron, let's chat about this on Monday and decide on a way forward.
