### ISSUE TITLE
Generate client and server options are missing from editor

### ISSUE THREAD

**Issue by Yoonwoo** [swagger-api/swagger-editor#1889]
Yesterday it was there, now its gone. Im confused.

Heres a picture of it.
http://web.ccpgamescdn.com/newssystem/media/73144/1/swagger_editor_1[1].png

That menu is gone now.
What...

**Comment by shockey** [comment]
Hey @Yoonwoo, the Generate menus depend on the generator.swagger.io service being available. 

That service was down for about 120 minutes starting five hours ago... which is why the menu disappeared 😄

I’m going to keep this open as an enhancement, sine we could probably do a better job of indicating what’s going on.

**Comment by shockey** [comment]
Closing as resolved - @Yoonwoo, if you're still having problems just reply here and I'll look into it.
