### ISSUE TITLE
How To Enable Designer Mode in Swagger Editor ?

### ISSUE THREAD

**Issue by Prasanthmv** [swagger-api/swagger-editor#276]
Hi, 
Please Help me  . The Designer mode is not get enabled in opera,chrome,Firefox . How can I enable this in my browser .?

**Comment by EricWittmann** [comment]
@mohsen1 - is the Designer implementation in progress?  If not, let me know - might have an idea for a collaboration.

**Comment by webron** [comment]
I'd like to be part of that discussion as well.

**Comment by mohsen1** [comment]
Hi @EricWittmann! I'm glad you're interested in helping. The plan is to have some UI controls like buttons for manipulating the swagger specs from preview panel. For example in parameters table, at the end of the table there should be button that says **"add a new parameter"** and clicking that button opens up a modal that has a form for making a new parameter (with all possible ways of making a parameter of course). Then after a parameter is created by that modal, we need to put that parameter back to specs. In case of JSON, it's simple because there is no comments and styling in JSON and regenerating all of JSON is fine. In case of YAML it's a bit trickier. We need to use ASTManager to insert the parameter exactly where it should be without re-generating the YAML from specs JavaScript object. We don't want to modify user's YAML structure or remove their comments. 

To get started, familiarize yourself with the project. There is a global `mode` variable that is accessible via `$rootScope.mode` in JS files or simply `mode` in templates. First step is to remove that alert and make the menu button override global mode. Then we want to add UI controls and limit their appearance to `ng-if="mode === 'designer'"` because those controls should be hidden in other modes.

Please start fiddling with the project and make a PR according to what I described. We can continue this discussion there.

**Comment by EricWittmann** [comment]
Hey thanks for the response, @mohsen1 - I'm not sure if this is the appropriate venue for this discussion, so am happy to move it somewhere else at your discretion.  :)  But very briefly let me be more specific than I was in my original cryptic post. lol

In the apiman project ( http://apiman.io/ ) we're likely going to be integrating swagger in the next few months.  The existing swagger tools are great, and we'll use them as-is.  I noticed that the Swagger Editor was a text editor (yaml editor with live preview) and thought it would be great to have something more Designer-like.  

Because it's not critical path to our project, and because it seems like a reasonably meaty contribution, I thought this might make a great senior project for one of the schools we work with for such things.  Then I saw the "Designer" menu item and thought "uh oh, I'd better run it past these guys first to see what they think".

So that was going to be my suggestion - if you're interested, we could come up with a set of requirements for a pie-in-the-sky visual/wysiwyg editor and get it implemented as a formal project.

If that sounds interesting, let me know.  If not, I totally understand!  :)

**Comment by prabhatjha** [comment]
@EricWittmann Thanks for your offer to help. We should be able to discuss here or on IRC at #swagger . I think it would be great to have some more UI handholding to guide people with defining API in Swagger. We can always do a google hangout. Are you up for that?

**Comment by EricWittmann** [comment]
Hey @prabhatjha - yeah I'm definitely up for a google hangout.  That's probably the fastest way to discuss this. :)  Let me know when.  I'll jump onto #swagger as well.  My IRC username is ewittman.
