### ISSUE TITLE
Error: Response 500

### ISSUE THREAD

**Issue by mathureshruti** [swagger-api/swagger-editor#2867]
Hello,

I am pretty new to swagger editor. I am trying to create documentation with username and password in request body  wuth basic Authentication. 
In the response I am getting code as 500. Below is a screenshort.
![image](https://user-images.githubusercontent.com/57104828/148922475-9b793caf-cbe2-4cb9-a6de-22ef2837b790.png)
 In Request Body i am using application/xml  and application/x-www-form-urlencoded as media type.

Can someone tell me how to remove this error?

Swagger Editor : version 3.0

**Comment by hkosova** [comment]
@mathureshruti do you use https://editor.swagger.io or SwaggerHub?

**Comment by mathureshruti** [comment]
Hi,
I am using https://app.swaggerhub.com i.e Swagger Hub

**Comment by hkosova** [comment]
Since you're using SwaggerHub, please use the in-app support chat
![image](https://user-images.githubusercontent.com/8576823/148940426-0ba06e24-252a-4253-a087-1a4e3fe3b57e.png)

or open a suport ticket at https://support.smartbear.com/swaggerhub/message

<br>

This repository is only for issues with the open-source Swagger Editor.
