### ISSUE TITLE
swagger-editor performance

### ISSUE THREAD

**Issue by gtinjr** [swagger-api/swagger-editor#337]
I have been using the editor for about a month now and while it is great to document the api and later to use with swagger-codegen to create the client and the jax-rs server.  It seems to get pretty slow in editor/preview mode after about 1000 lines.

I have about 2000 lines on my yaml.  Running either remote on an ec2 box or locally on a iMac core i7, I experience slowness.  

By slowness, I mean it takes 10 seconds to delete a blank line. I tried with latest firefox and chrome browsers and that does not seem to make a difference.

Is there anything I can try to improve the performance?

Thx

**Comment by mohsen1** [comment]
You can select **Mode > Disable Live Render** to disable per keypress updates. This will help you edit large Swagger spec documents.

**Comment by prabhatjha** [comment]
However I think this is a great feedback and we would need to debug perf issue. I am sure it can be improved.

**Comment by mohsen1** [comment]
Yes, we can write our own diffing algorithm to update DOM partially. AngularJS is very good at doing this *if we keep the source specs the same object*, but what we override the source specs object each time user press a key because we transform hashes to arrays to keep the ordering right.
One solution is to not override the source object and perform a deep diff and update only parts that are changed. 
I'll look into it in feature

**Comment by mohsen1** [comment]
With a56cd98eaab8b08c63813787b825b69a87515cf2 the diffing and rendering speed has improved dramatically because we are doing the diff in JS land instead of overriding Angular's scope. Let me know if you're still having issues with performance.
