### ISSUE TITLE
Swagger-editor in react giving the error 

### ISSUE THREAD

**Issue by satishbkodali** [swagger-api/swagger-editor#3971]
```
**Error**
schema with key or id "openapi-2.0" already exists

**Call Stack**
 n._callbacks.
  node_modules/swagger-editor/dist/swagger-editor-es-bundle.js:4:860475
 r
  node_modules/swagger-editor/dist/swagger-editor-es-bundle.js:4:860219
 Worker.eval
  node_modules/swagger-editor/dist/swagger-editor-es-bundle.js:4:860323
```

We are swagger-editor in backstage app that also has swagger-ui already builtin. How do we get pass this issue

@char0n I noticed you might have same issue. We are using latest version of swagger-editor

**Comment by char0n** [comment]
Hi @satishbkodali,

Thanks for the report, but there is inefficient information to act on it. 

Here is the issue template that needs to be filled so that we can act on it:

---



### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration


Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering


### To reproduce...

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior


### Screenshots


### Additional context or thoughts
