### ISSUE TITLE
Multiline text values in the YAML do not export nicely

### ISSUE THREAD

**Issue by kal** [swagger-api/swagger-editor#422]
You can see this by downloading the YAML for any API definition containing multiline text (e.g. in a description field). In the GUI, the YAML is formatted as:

    description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array

In the downloaded YAML this is serialized as:

    description: "Gets `Person` objects.\nOptional query param of **size** determines\nsize of returned array\n"

Although it is the same thing in terms of the data, it does make for a poor editing experience when you then upload the YAML to the editor again.

**Comment by mohsen1** [comment]
It's because of [this line](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/controllers/header.js#L156). We're doing that because people might be using JSON instead of YAML in the editor. I think we should put this line behind a condition that checks if there is JSON in the code
