### ISSUE TITLE
Console error when changing swagger key in Swagger 2.0 spec

### ISSUE THREAD

**Issue by damian-polewski-sb** [swagger-api/swagger-editor#4697]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 120
 - Method of installation: npm
 - Swagger-Editor version: 4.11.2
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
This issue is present on the hosted version of Swagger-Editor accessible here: https://editor.swagger.io/
I tested this issue with Petstore OAS2.0.

### Describe the bug you're encountering
When replacing the key `swagger` with `openapi` there is an error in the console: `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`. 
The issue is not present here: https://editor-next.swagger.io/

### To reproduce...

1. Go to https://editor.swagger.io/
2. Open the browser console
3. Click on 'Edit' dropdown button
4. Click on 'Load Petstore OAS2.0' button
5. Replace the key `swagger` with `openapi`
6. See error

### Expected behavior
SwaggerUI displays `Unable to render this definition` but no console error is visible.

### Screenshots
<img width="1728" alt="Screenshot 2024-01-09 at 15 26 56" src="https://github.com/swagger-api/swagger-editor/assets/125268832/ff833315-76ca-4d57-aa4e-5155d4d61a10">

**Comment by char0n** [comment]
The same happens with the reverse action of replacing the key `openapi` with `swagger`.

The issue is that in cases like this, the definitions becomes unknown as there is no `openapi: 2.0` or `swagger: 3.0.3`. The `validateImmediate` function only compensate for the ambiguity of detecting the definition as both, but not the situation that the definition is not detected as OpenAPI definition at all.
