### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by kalinchernev** [swagger-api/swagger-editor#479]
Trying to only run the npm start does not build and run the project as expected. Looks like having to update dependency packages.

```shell
kalin:swagger-editor$ npm start

> swagger-editor-src@2.9.6 prestart /home/kalin/swagger-editor
> npm run build


> swagger-editor-src@2.9.6 prebuild /home/kalin/swagger-editor
> npm run bower-install


> swagger-editor-src@2.9.6 prebower-install /home/kalin/swagger-editor
> npm install

npm WARN package.json swagger-editor-src@2.9.6 No license field.
npm WARN deprecated grunt-bower-install@1.6.0: use grunt-wiredep instead
npm WARN peerDependencies The peer dependency mocha@* included from karma-mocha will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> cson@1.6.2 preinstall /home/kalin/swagger-editor/node_modules/load-grunt-config/node_modules/cson
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /home/kalin/swagger-editor/node_modules/load-grunt-config/node_modules/cson/node_modules/ambi
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /home/kalin/swagger-editor/node_modules/load-grunt-config/node_modules/cson/node_modules/ambi/node_modules/typechecker
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /home/kalin/swagger-editor/node_modules/load-grunt-config/node_modules/cson/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

 
> js2coffee@0.3.5 preinstall /home/kalin/swagger-editor/node_modules/load-grunt-config/node_modules/cson/node_modules/js2coffee
> node ./cyclic.js

npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing graceful-fs@^3.0.5
npm WARN optional dep failed, continuing request@2.57.0
|
> bufferutil@1.1.0 install /home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.1.0 install /home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/kalin/swagger-editor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/build'
npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.11.0
npm ERR! path /home/kalin/.npm/clean-css/3.3.1
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/home/kalin/.npm/clean-css/3.3.1'
npm ERR!  { [Error: EACCES, mkdir '/home/kalin/.npm/clean-css/3.3.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/kalin/.npm/clean-css/3.3.1',
npm ERR!   parent: 'grunt-contrib-cssmin' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalin/swagger-editor/npm-debug.log

npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "bower-install"
npm ERR! node v0.10.37
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prebower-install: `npm install`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.6 prebower-install script 'npm install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalin/swagger-editor/npm-debug.log

npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.10.37
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prebuild: `npm run bower-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.6 prebuild script 'npm run bower-install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalin/swagger-editor/npm-debug.log

npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.37
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.6 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalin/swagger-editor/npm-debug.log
kalin:swagger-editor$ 
```

**Comment by mohsen1** [comment]
Please try removing all your node modules and clearing cache. Then start again, if that didn't help let me know.

```
rm -rf node_modules app/bower_components
npm cache clean 
bower cache clean
npm start
```

Also I see you're using node `0.10` which is very old. Try updating your node engine also. We have no problem with node `0.10` but it's less stable in our [build matrix](https://travis-ci.org/swagger-api/swagger-editor/builds).

**Comment by kalinchernev** [comment]
Many thanks for the quick reply! The clear-cache actions had to be twice for me, in the end it started and works.

Greatly appreciated!

**Comment by mohsen1** [comment]
:+1:

**Comment by pengqiuyuan** [comment]
[root@10 swagger-editor]# bower cache clean
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
[root@10 swagger-editor]# bower cache clean --allow-root
bower deleted       Cached package SparkMD5: /root/.cache/bower/packages/f0e96b6ed9aecd867792e2c201a9ecd6/0.0.5
bower deleted       Cached package angular: /root/.cache/bower/packages/ef2188def21eb1bbd1f1792311942a53/1.3.15
bower deleted       Cached package angular-bootstrap: /root/.cache/bower/packages/4fb30846af9d14960a8cdb35aa9f8f19/0.13.0
bower deleted       Cached package angular-cookies: /root/.cache/bower/packages/87323d6d4e48be291a9616a033d4cc6c/1.3.15
bower deleted       Cached package angular-marked: /root/.cache/bower/packages/15016f8f87149164244e87dc22a90710/0.0.17
bower deleted       Cached package angular-mocks: /root/.cache/bower/packages/e9f8053314f992cbc734f1d338e7339c/1.3.15
bower deleted       Cached package angular-resource: /root/.cache/bower/packages/d751baf3abe66bad059ba9b95cbb13a6/1.3.15
bower deleted       Cached package angular-sanitize: /root/.cache/bower/packages/9eaed103d6a7e78d91f673cfad796850/1.3.15
bower deleted       Cached package angular-scenario: /root/.cache/bower/packages/b14760da33b10f217074c8db0293d643/1.3.15
bower deleted       Cached package angular-ui-ace: /root/.cache/bower/packages/7456884cedce48fd6c954363760ff452/0.2.3
bower deleted       Cached package angular-ui-layout: /root/.cache/bower/packages/d33f5ef46357f27e3284907c3a788d1a/1.0.5
bower deleted       Cached package apply-diff: /root/.cache/bower/packages/9ef348bbb07362ee7181346b8a948711/1.2.5
bower deleted       Cached package es5-shim: /root/.cache/bower/packages/48ba6a0b92a9b54919af0c93adc1053b/4.1.8
bower deleted       Cached package lodash: /root/.cache/bower/packages/cc6d3adf8c2a36f7b163cc9479c3829c/3.9.3
bower deleted       Cached package lodash: /root/.cache/bower/packages/cc6d3adf8c2a36f7b163cc9479c3829c/3.10.0
bower deleted       Cached package lodash-compat: /root/.cache/bower/packages/489af1d184b9346ef85d0d68bd5efc35/3.8.0
bower deleted       Cached package ng-file-upload: /root/.cache/bower/packages/b3119113c333700fef5a047c8bce705e/5.0.9
bower deleted       Cached package ngstorage: /root/.cache/bower/packages/9ff0a7f5225539b6a0b0944d1002af1b/0.3.7
bower deleted       Cached package raf: /root/.cache/bower/packages/09a63ff3d468707bff991a99909db5a9/_wildcard
bower deleted       Cached package swagger-converter: /root/.cache/bower/packages/7f95a9939a4e72664ec6526b801a6beb/0.1.7
bower deleted       Cached package yaml-js: /root/.cache/bower/packages/93445775a056acea3abf461420024407/0.1.1
bower deleted       Cached package angular-ui-router: /root/.cache/bower/packages/62c903e33a8a6ef032774d5ca73673d9/0.2.15
bower deleted       Cached package async: /root/.cache/bower/packages/22b187db412f52408cfde79132eef9c1/0.9.2
bower deleted       Cached package js-traverse: /root/.cache/bower/packages/5dd484603631f0d76a2af146eb11d30c/0.6.7
bower deleted       Cached package json-editor: /root/.cache/bower/packages/fec33c4b353656796f9ab24e703c3061/0.7.21
bower deleted       Cached package json-formatter: /root/.cache/bower/packages/e6959527d897778f1b3cf3cfed86ad19/0.3.0
bower deleted       Cached package json-refs: /root/.cache/bower/packages/03c179dc0e949b39fabd1d56478f78e6/0.2.0
bower deleted       Cached package json-schema-view: /root/.cache/bower/packages/26df9f550fcbcbb850d56864a250a786/0.4.2
bower deleted       Cached package json3: /root/.cache/bower/packages/5b1ce4d7f2e8368c9df0c4e49d95b130/3.3.2
bower deleted       Cached package marked: /root/.cache/bower/packages/f046509b868d7c98fd981ef99ac79e73/0.3.3
bower deleted       Cached package objectpath: /root/.cache/bower/packages/a0c785af8be9bfffad1232aa4d66537d/1.2.1
bower deleted       Cached package schema-form: /root/.cache/bower/packages/17803236c0b51a855e6ebd688a5b6dc3/0.1.1
bower deleted       Cached package swagger-tools: /root/.cache/bower/packages/3cd6583931282b4bacca3f0536472950/0.8.7
bower deleted       Cached package visionmedia-debug: /root/.cache/bower/packages/33c6320d048a4d8419e25b0ed18e5781/2.1.3
bower deleted       Cached package bootstrap: /root/.cache/bower/packages/76825ba06db421bbfbda0853e440b3f5/3.3.5
bower deleted       Cached package path-loader: /root/.cache/bower/packages/f2fe99890631d5986090e265a1b4ef1f/0.0.2
bower deleted       Cached package ace-builds: /root/.cache/bower/packages/9ed38525cbe603a13619923875a2e96d/1.1.9
bower deleted       Cached package jquery: /root/.cache/bower/packages/fe2fe255e91d251051d543998aa8327a/2.1.4
bower deleted       Cached package js-yaml: /root/.cache/bower/packages/26688750e710b26e22455ad878ca5d40/3.3.1
bower deleted       Cached package z-schema: /root/.cache/bower/packages/6010e2daef6b09acc42ec4e8463de3fa/3.12.0
[root@10 swagger-editor]# ^C

**Comment by pengqiuyuan** [comment]
rm -rf node_modules app/bower_components
npm cache clean 
bower cache clean --allow-root
npm start
