### ISSUE TITLE
Allow fragment edition for REUSE usage

### ISSUE THREAD

**Issue by danielm64** [swagger-api/swagger-editor#536]
The [REUSE philosophy](https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md) relies on YAML fragments for:
•Operations
•Parameters
•Responses
•Models 

Editing these fragments is not supported by swagger-editor.
 Currently, we write full swagger 2.0 specs, and, when complete and valid, comment all what should not be in the fragment... 
 would appreciate this support to suppress the unnecessary work...

**Comment by mohsen1** [comment]
I understand what the requirement is but I don't know how this should be implemented. Problem is, it's impossible to tell if you're writing a fragment or the Swagger spec is just invalid.


@webron Does Swagger have a method for marking fragment files? Something like specifically formatted comments maybe?

**Comment by webron** [comment]
That's a fair question, but the answer is no. Eventually, it's just YAML/JSON files. The 'root' file, representing the Swagger object, has a specific structure (as you know), but the fragments can pretty much be anything.

That means that the validation could be done only from the root file, as that's the only time you can assign a meaning to the referenced objects. And yes, that makes auto-complete and so on more complicated. I can possibly think of a few ways to ease up the implementation (in terms of user experience), but perhaps we should discuss that separately? May be easier.

**Comment by mohsen1** [comment]
For Swagger Editor to support this we can have some specific comments. Here is my proposal for the spec of the comments I that indicates a YAML file is a partial swagger file:

1. First line MUST be a comment
2. Comment body is formatted as follows and containing  `# partial-swagger: ` (space, `partial-swagger`, colon, space)

   `# partial-swagger: {{path}}`
3. the `path` component can be a string or a JavaScript array. 
4. If path is string it is pointing to a root object in swagger document.
  
  Example: 
  ```yaml
  # partial-swagger: info
  title: My API
  description: An API
  ```
5. If path is an array it is pointing to an object deep inside the swagger document. It should be valid JavaScript(or JSON) array
  Example:

  ```yaml
  # partial-swagger: ["info", "contact"]
  email: me@example.com
  url: example.com
  name: My Name
  ```

Obviously this is not part of Swagger spec and it's here only to help Swagger Editor work with partial YAMLs that build up a larger spec.

@webron @fehguy Please review

**Comment by danielm64** [comment]
Hi,

No news... 
@webron @fehguy can you please review @mohsen1 proposal ?

Thanks.

**Comment by fehguy** [comment]
@mohsen1 does this mean you're suggesting support of non-swagger spec files inside the editor, by using the comment as the indicator?

**Comment by mohsen1** [comment]
Yes, there is no way to know if Swagger is invalid or it's just a part of a larger spec.

**Comment by webron** [comment]
The comments way is probably the only way to go due to obvious limitations.

A few questions/comments:
- Can you please clarify the example of the array? I'm not sure I understand what you mean by it.
- Are you going to perform partial validation on those segments?
- This kind of implementation forces a structure of the segments. I don't mind it, though some people may expect something slightly different. We can try breaking it down further and see if/how we'd want to support more cases. I'm okay with basic support at first.

**Comment by mohsen1** [comment]
> Can you please clarify the example of the array? I'm not sure I understand what you mean by it.

The array is a made up format for "path" to this partial from root of the spec. I guess we're better off using   [JSON Pointer (RFC 6901)](https://tools.ietf.org/html/rfc6901) for that. 

> Are you going to perform partial validation on those segments?

My thinking is to fill in the missing parts with minimal swagger and validate the whole thing. It would be a lot of work to support partial validation in swagger-tools

> This kind of implementation forces a structure of the segments. I don't mind it, though some people may expect something slightly different. We can try breaking it down further and see if/how we'd want to support more cases. I'm okay with basic support at first.

I can't think of anything other than breaking down swagger into smaller files that are pieces of a larger spec. I would love to see different ways of doing it though...

**Comment by webron** [comment]
Oh, so by this example:

```yaml
# partial-swagger: ["info", "contact"]
email: me@example.com
url: example.com
name: My Name
```
You meant Contact object under Info? (I'm ignoring that this is not really a 'reuse' use case)

---

I believe partial validation is going to be requested as soon as there's ability to split files. If there's not going to be partial validation, I'm not sure there's a reason for the first-line comment (other than saying it shouldn't be validated at all, but you don't need to define the 'path' in it).

---

To clarify, it's technically possible to have something like (and forgive my json):

```json
{
  "mypersonaldefs": {
    "modelX" {
      "type": "object"
    }
  }
}
```

and `$ref`'ing it from the root Swagger as `/path/to/file#/mypersonaldefs/modelX`. However, it's not really 'definitions' and it's not really a single definition in that file. We may say initially that we don't support this use case, but it's technically feasible.

---

And on that note, how will the multi-files be referenced each other? What would be the path?

**Comment by mohsen1** [comment]
Because editor is not owning the spec in it's host, there is no way to resolve relative and fragments paths. the only ref we can resolve is absolute refs

**Comment by webron** [comment]
Okay, I have a couple of thoughts on resolving relative fragments as well, but that can be phase 2. What about the other points? :)

**Comment by glen-84** [comment]
> and $ref'ing it from the root Swagger as /path/to/file#/mypersonaldefs/modelX. However, it's not really 'definitions' and it's not really a single definition in that file.

This is what we're doing, FWIW. Well, the model definition file (with one or more definitions) is referenced from an operation file, which is then referenced from the main file.

We don't have the `mypersonaldefs` container key though.

**Comment by andylowry** [comment]
I'm not a fan of specifying where a fragment belongs in the root spec, within the fragment itself. If I'm reusing something in more than one root spec, I may want it to be accessed by different paths in those specs. Or if want to reference it more than once in a single spec, I'm forced to place it in some placeholder in the root spec and then use local refs where I want the fragment to appear.

The existing support for JSON refs seems adequate with the sole exception of not supporting the editing of fragments, and it avoids the issue of nailing down in the fragment where it belongs in any root spec that references it.

Since the only limitation occurs during editing, it seems that comments are not required at all - merely an editor GUI option to state that the fragment is not a Swagger spec (and so should be treated as a plain JSON or YAML object by the editor). The editor could even be smart enough to offer, when it loads an object without `swagger` root property, to switch to non-swagger editing mode, or silently default to that and dynamically switch if a `swagger` root property is added. Or whatever...

**Comment by mohsen1** [comment]
@andylowry Your points are very valid. Having a GUI instead of comments to indicate you're working on a fragment is a good idea. That will not pollute the document with comments just for the sake editing. 

I'm not sure about automatically switching to fragment editing mode. In the world of invalid documents a lot of things can go wrong and all of that "smartness" can overcomplicate stuff.

**Comment by andylowry** [comment]
Makes sense re the automatic switch. Still it might be helpful to
    have it offered when a syntactically valid object is loaded without
    a 'swagger' root element. It would avoid the hassle and ugliness of
    loading a non-swagger document and then putting up with the error
    messages until the editing mode is manually switched.
    
    On 8/27/2015 2:02 PM, Mohsen Azimi
      wrote:
    
    
      @andylowry Your points are very
        valid. Having a GUI instead of comments to indicate you're
        working on a fragment is a good idea. That will not pollute the
        document with comments just for the sake editing. 
      I'm not sure about automatically switching to fragment editing
        mode. In the world of invalid documents a lot of things can go
        wrong and all of that "smartness" can overcomplicate stuff. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by saharj** [comment]
#1000 will fix this. Please check it out.

**Comment by danielm64** [comment]
Hi @saharj ,

The #1000 fix does not address really this initial request of this issue...
But, if I understand all, support of reusable fragments separated from pure and complete Swagger 2.0 document is abandonned...
If so, reject this enahancement request.

**Comment by saharj** [comment]
That's correct. With that change you can edit Swagger files that uses fragments that are referenced with a relative path such as './foo.yaml' but it will not be able to edit those fragments. 

Editing the fragments is not completely out of scope of this project so i will keep this issue open. Although I dont know how we can allow such thing at the moment.

**Comment by webron** [comment]
For now, this will not be supported by the editor.

**Comment by chris922** [comment]
Sorry I only rushed through the comments. 

But the issue here is how to recognize to which part the fragment belongs to display it correctly in the live preview?
Isn't it just possible to say file X is my main file which includes the fragments and thus always display file X in the preview. When opening a fragment there is still file X displayed which will be rerendered in case the opened fragment will be changed?

We are working with a > 5.000 lines swagger file which is very hard to maintain, but we haven't found yet a good solution to split it up in multiple files and still be able to use the Swagger editor..

**Comment by andylowry** [comment]
@chris922 You might want to take a look at [RepreZen API Studio](https://www.reprezen.com). It includes a generator ("GenTemplate"in API Studio lingo) called "Swagger Normalizer" that can turn a multi-file swagger specification into an equivalent single file, suitable for software that does not deal well with multifile specifications.

There's a [youtube video](https://www.youtube.com/watch?v=xKhNAQuq1x0) that talks more broadly about API Studio's support for multi-file swagger specifications.

[Disclaimer: I work for RepreZen]
