### ISSUE TITLE
Where does swagger-editor save in-progress specs?

### ISSUE THREAD

**Issue by SteveNewhouse** [swagger-api/swagger-editor#572]
I'm trying to retrieve work that was in progress but not exported.  Is it lost?

**Comment by mohsen1** [comment]
If you closed the tab before editor showing "saved" message in status bar your changes are lost unfortunately

**Comment by timfogarty1549** [comment]
And when the browser crashes everything is lost too.  A recover system is needed.

**Comment by zcwang3** [comment]
drap or user File menu to open a yaml file and do some changes.
where is changes saved when "All changes saved" is showed in browser?
original file is not changed!

**Comment by tagyoureit** [comment]
Just a comment that it since the local browser storage is used it makes a difference in what URL is pulled up.  I just ran into this and loaded http://127.0.0.1:3001 from the local browser and thought I lost everything but it was actually stored under the cache of the browser under http://localhost:3001.

**Comment by shockey** [comment]
@tagyoureit this is a good point.

Since browser security policies keep localStorage instances segmented by [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin), there's not anything we can do to detect/warn the user about this that wouldn't require us to maintain a cross-origin hub server-side (which a lot of people wouldn't want an open-source project to do).
