### ISSUE TITLE
Localization of labels, titles.

### ISSUE THREAD

**Issue by nacho4d** [swagger-api/swagger-editor#591]
Swagger looks really nice!. It would be even better if I the server can show me localised labels in an specific language (provided a query parameter in the url or by reading the Accepted-Languages request header, etc)

I know API documentation/specifications for big projects are usually written in english but if swagger is used for some local/internal projects then probably the local language will be used (Japanese in my case). 

Currently I can write the documentation in Japanese but the titles, labels, etc are still in english. Wouldn't it be nice to have a localised string for those? I don't expect labels in the yaml file to be changed. Just the result document/html. So basically current document:

<img width="1440" alt="screen shot 2015-08-18 at 17 08 27" src="https://cloud.githubusercontent.com/assets/111651/9325342/8d135494-45cc-11e5-9d0d-384cb8483cab.png">

would become:

<img width="1440" alt="localized" src="https://cloud.githubusercontent.com/assets/111651/9325679/0ea5bbda-45cf-11e5-8cac-6c0bb40a91d9.png">

(By labels I meant words like Summary->概要, Description→説明, Parameters→パラメーター, Responses→リスポンス, Code→コード, Default→デフォルト, etc...)

**Comment by webron** [comment]
Thanks, but this has nothing to do with swagger-editor. It's a feature request to swagger-spec which exists here - https://github.com/swagger-api/swagger-spec/issues/274. Feel free to add your comments there.

**Comment by nacho4d** [comment]
I see... Thanks for the link. I will write something there

**Comment by mohsen1** [comment]
Localization of labels in Swagger Editor is something we can do, although it's a very low priority. We should use something like [angular translate](https://angular-translate.github.io/docs/#/guide) to achieve it. Instead of using a query parameter we can use standard `Accept-Language` header. We can have a query parameter that overrides `Accept-Language`. That would be nice.

Providing translation in spec `description` and `summary` is something that might come in next Swagger spec. When it landed in spec, editor should also show correct language entry for `description`.

**Comment by nacho4d** [comment]
> We can have a query parameter that overrides Accept-Language. 

:+1:

**Comment by webron** [comment]
Closing as an old issue. Please file a new one if still relevant.
