### ISSUE TITLE
Closing "try it" clears out test data.

### ISSUE THREAD

**Issue by LeBlaaanc** [swagger-api/swagger-editor#691]
Could we just collapse this instead?

**Comment by saharj** [comment]
That's right, and it's because it uses [a `ng-if`](https://github.com/swagger-api/swagger-editor/blob/master/app/templates/operation.html#L209). The problem can be solved by using `ng-show` or `ng-hide`, but this way we'll have much more HTML elements that slow downs the app, so we prefer to keep the code as it is now.
