### ISSUE TITLE
Examples are not validated against schema

### ISSUE THREAD

**Issue by lldata** [swagger-api/swagger-editor#738]
If I specify an operation with both a schema and one or more examples, I would expect that the examples are validated against the schema.

Current behavior: The examples are not validated in any way.

Some kind of basic validation (just names and structure) are better than none.

```yaml
swagger: "2.0"
info:
  title: Simple API overview
  version: v2
paths:
  /:
    get:
      operationId: listVersionsv2
      summary: List API versions
      produces:
      - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/response'
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "versions": [
                      {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "id": "v2.0",
                          "links": [
                              {
                                  "href": "http://127.0.0.1:8774/v2/",
                                  "rel": "self"
                              }
                          ]
                      },
                      {
                          "status": "EXPERIMENTAL",
                          "updated": "2013-07-23T11:33:21Z",
                          "id": "v3.0",
                          "links": [
                              {
                                  "href": "http://127.0.0.1:8774/v3/",
                                  "rel": "self"
                              }
                          ]
                      }
                  ]
              }
 
definitions:
  response:
    type: object
    properties:
      versions:
        type: array
        $ref: '#/definitions/api'
    
  api:
    type: object
    properties:
      status:
        type: string
      updated:
        type: string
      id:
        type: string
      links:
        type: array
        $ref: '#/definitions/link'

  link:
    type: object
    properties:
      href:
        type: string
      rel:
        type: string
```

**Comment by saharj** [comment]
* When you use a pipe, all the object becomes a multiline string.
* By design swagger does not check the response schema with examples. If you want to go into more details see [here](https://github.com/OAI/OpenAPI-Specification).


<img width="1421" alt="screen shot 2016-01-28 at 9 47 08 pm" src="https://cloud.githubusercontent.com/assets/1468463/12668174/bc75061c-c608-11e5-82a0-6dce25ff8c56.png">

**Comment by jookshub** [comment]
Is there any available tooling to validate examples against the schema?

This is a big gap in an otherwise very helpful workflow.

Create a spec -> add example data -> generate server code -> have a mock api ready to use

Of course it works without the validation, but the point of this workflow is to have a schema compliant mock api with valid example data. If you think it further, if it would be possible to import example data thought "ref" imports, this would be a very powerful feature, as you could specify some basic mock data for the api for testing purposes an have it already validated.

Is there anybody who has something like this set up already?

**Comment by webron** [comment]
That's right, the schema doesn't enforce it because the *spec* doesn't enforce it. There may be tools out there that will help with it, but it's outside the scope of the spec.
