### ISSUE TITLE
A simple docker image for deployment

### ISSUE THREAD

**Issue by kepkin** [swagger-api/swagger-editor#740]
Hi!

Right now the Dockerfile you have in the repository is good for building and testing code. However, it's not suitable for actual deployment as it's several gigabytes in size.

I've built a much simple docker image just for deployment and it contains only `dist` folder and based on nginx. It's 147 MB in size.
https://hub.docker.com/r/kepkin/swagger-editor/

I would love to create a separate GitHub repository just for building this distribution docker image, but I need a simple way to download swagger-editor build result.

Can you configure Travis to publish GitHub releases so I could download a prebuilt package?

**Comment by fehguy** [comment]
Please take a look at https://hub.docker.com/r/swaggerapi/swagger-editor/

It is now simply serving up pre-build code as you are, and is maintained by pushing to `latest` on each commit to master.  In addition, tags will be auto-deployed to dockerhub.

If you have improvements to the image, please feel free to send a PR!

**Comment by kepkin** [comment]
359.1 MB in size. That's still a lot :-( Will you accept nginx as a serving application server instead of node-http-server?

**Comment by fehguy** [comment]
Yes, if you think that'll do it

**Comment by thomaslprr** [comment]
Hello @fehguy ,
I have a question about deployment via Docker. 
I love the concept but I would like to have the command to launch in "offline" mode the Docker. Because at the moment, when I launch the Docker commands, it creates Swagger Editor locally but it needs an internet connection to be powered. I would like to keep the same principle but without needing the internet connection.

In other words, how to use swagger-editor-dist via Docker? 
Thanks a lot in advance
