### ISSUE TITLE
Feature request: add reset-content cmd/button

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-editor#883]
I'd like to be able to clear all content from the editor quickly (e.g. by clicking a button).

This is not only for convenience to alternative "CTRL+A, then DEL": when working with large content, this is a must, because selecting all content becomes a very slow task (first, I have to let the editor finish whatever it's doing in the background, as it blocks the UI completely; then selecting-all is also slow, etc), and - more importantly - because the content survives browser-restart (I noticed it's in localStorage), while Chrome's dev-tools window (amazingly; pun intended) crashes every time when even the site-level Local Storage node is as little as selected (mouse-click).

Perhaps improving the editor slightly to not block the UI as much would be helpful. 

Possibly related: https://github.com/swagger-api/swagger-editor/issues/882

**Comment by webron** [comment]
The new version of the editor has a clear editor menu item under `File`.

**Comment by danidemi** [comment]
Hi @webron, 
I add my experience related to this problem.

1. I pasted in the editor, running on FF, a huge OpenAPI 3 spec.
1. It was full of error, so FF hangs up with the usual "a script is taking too much to complete".
1. Now... if I stop the script, I cannot clear the content because I suppose the menu item under `File` you mentioned does not work.
1. If I don't stop the script, I cannot click the menu item either because the browser is blocked.

So, I think there should be another way to clear the content. Hope my experience helps.

**Comment by webron** [comment]
The experience is clear, but right now there's no functionality we can add to avoid it. We're working on improving the performance and that should much such issues be avoided in the future.
